package com.example.streetshelter.ui.theme

import androidx.compose.ui.graphics.Color

// Main brand colors from the logo
val LogoOrange = Color(0xFFF57F17)
val LogoBlue = Color(0xFF003764)

// Generated Material 3 color scheme

// Light Theme Colors
val md_theme_light_primary = Color(0xFF8C5000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDBA)
val md_theme_light_onPrimaryContainer = Color(0xFF2D1600)
val md_theme_light_secondary = Color(0xFF725B42)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFEDDBE)
val md_theme_light_onSecondaryContainer = Color(0xFF281806)
val md_theme_light_tertiary = Color(0xFF55643B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE9B6)
val md_theme_light_onTertiaryContainer = Color(0xFF131F00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F5)
val md_theme_light_onBackground = Color(0xFF211A13)
val md_theme_light_surface = Color(0xFFFFF8F5)
val md_theme_light_onSurface = Color(0xFF211A13)
val md_theme_light_surfaceVariant = Color(0xFFF2E0D0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF837568)
val md_theme_light_inverseOnSurface = Color(0xFFFDEEE3)
val md_theme_light_inverseSurface = Color(0xFF362F27)
val md_theme_light_inversePrimary = Color(0xFFFFB967)
val md_theme_light_surfaceTint = Color(0xFF8C5000)
val md_theme_light_outlineVariant = Color(0xFFD5C4B4)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFFFB967)
val md_theme_dark_onPrimary = Color(0xFF4B2800)
val md_theme_dark_primaryContainer = Color(0xFF6B3B00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDBA)
val md_theme_dark_secondary = Color(0xFFE0C1A3)
val md_theme_dark_onSecondary = Color(0xFF402D18)
val md_theme_dark_secondaryContainer = Color(0xFF59432C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFEDDBE)
val md_theme_dark_tertiary = Color(0xFFBEDD9C)
val md_theme_dark_onTertiary = Color(0xFF283510)
val md_theme_dark_tertiaryContainer = Color(0xFF3E4C25)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE9B6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF211A13)
val md_theme_dark_onBackground = Color(0xFFEDE0D5)
val md_theme_dark_surface = Color(0xFF211A13)
val md_theme_dark_onSurface = Color(0xFFEDE0D5)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C4B4)
val md_theme_dark_outline = Color(0xFF9E8E80)
val md_theme_dark_inverseOnSurface = Color(0xFF211A13)
val md_theme_dark_inverseSurface = Color(0xFFEDE0D5)
val md_theme_dark_inversePrimary = Color(0xFF8C5000)
val md_theme_dark_surfaceTint = Color(0xFFFFB967)
val md_theme_dark_outlineVariant = Color(0xFF504539)
val md_theme_dark_scrim = Color(0xFF000000)
